# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1430872063);
user_pref("app.update.lastUpdateTime.background-update-timer", 1430872773);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1430872058);
user_pref("gfx.color_management.mode", 0);
user_pref("idle.lastDailyNotification", 1430911969);
user_pref("layout.scrollbar.side", 1);
user_pref("mozilla.widget.disable-native-theme", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.last_vacuum", 1429338752);
user_pref("plugin.scan.plid.all", false);
