sudo: required
install:
- which java
- java -version
- whoami
before_script:
- unzip ./vanillacontentcompiled.zip
- jar uf ./vanillacontentcompiled/imvuContent.jar ./XMVU/imvucontent.jar/*
script: true