IMVU = IMVU || {};
IMVU.translatedThemeNames = {
    'Loading': _T('Loading'),
    'Welcome': _T('Welcome'),
    'Other':_T('Other'),
    'Beach':_T('Beach'),
    'Getaways':_T('Getaways'),
    'Fantasy':_T('Fantasy'),
    'Furries':_T('Furries'),
    'Clubs & Lounges':_T('Clubs & Lounges'),
    'Outdoor Fun':_T('Outdoor Fun'),
    'Seasons & Holidays':_T('Seasons & Holidays'),
    'Homes & Offices':_T('Homes & Offices'),
    'Castles & Kingdoms':_T('Castles & Kingdoms'),
    'Art & Fashion':_T('Art & Fashion'),
    'Dark & Mysterious':_T('Dark & Mysterious'),
    'Clubs':_T('Clubs'),
    'Lounges':_T('Lounges'),
    'Vamp':_T('Vamp'),
    'Goth':_T('Goth'),
    'St. Patrick\'s Day Party':_T('St. Patrick\'s Day Party'),
};